networks:
  task-tracker-net:
    driver: bridge

services:
  config-server:
    container_name: config-server
    image: mrshoffen/task-tracker-config-server:latest
    networks:
      - task-tracker-net
    ports:
      - "8012:8012"
    env_file:
      - ./vars.env
    #    TODO add healthcheck
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8012/actuator/health/readiness" ]
      interval: 5s
      timeout: 2s
      retries: 10
      start_period: 5s

  discovery-service:
    container_name: discovery-service
    image: mrshoffen/task-tracker-discovery-service:latest
    networks:
      - task-tracker-net
    ports:
      - "8015:8015"
    env_file:
      - ./vars.env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8015/actuator/health/readiness" ]
      interval: 5s
      timeout: 2s
      retries: 10
      start_period: 5s
    depends_on:
      config-server:
        condition: service_healthy

  user-profile-ws:
    container_name: user-profile-ws
    image: mrshoffen/task-tracker-user-profile:latest
    networks:
      - task-tracker-net
    env_file:
      - ./vars.env
    depends_on:
      discovery-service:
        condition: service_healthy
      postgres:
        condition: service_started

  authentication-service:
    container_name: authentication-service
    image: mrshoffen/task-tracker-authentication-service:latest
    networks:
      - task-tracker-net
    env_file:
      - ./vars.env
    depends_on:
      discovery-service:
        condition: service_healthy
      postgres:
        condition: service_started

  api-gateway:
    container_name: api-gateway
    image: mrshoffen/task-tracker-api-gateway:latest
    networks:
      - task-tracker-net
    ports:
      - "8080:8080"
    env_file:
      - ./vars.env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health/readiness" ]
      interval: 5s
      timeout: 2s
      retries: 10
      start_period: 5s
    depends_on:
      discovery-service:
        condition: service_healthy
      redis:
        condition: service_started

  postgres:
    container_name: postgres_task
    image: postgres:17
    networks:
      - task-tracker-net
    env_file:
      - ./vars.env

  redis:
    container_name: redis_task
    image: redis:7.4
    networks:
      - task-tracker-net
    env_file:
      - ./vars.env