services:
  postgres:
    container_name: postgres_task
    image: postgres:17
    ports:
      - "3535:5432"
    networks:
      - task-tracker-net
    env_file:
      - ./vars.env
  environment:
    POSTGRES_SHARED_BUFFERS: 4GB
    POSTGRES_MAX_CONNECTIONS: 200

  redis:
    container_name: redis_task
    image: redis:7.4
    networks:
      - task-tracker-net
    env_file:
      - ./vars.env