services:
  task-frontend-service:
    container_name: task-frontend
    image: mrshoffen/task-tracker-frontend:latest
    ports:
      - "80:80"

  image-service:
    container_name: image
    image: mrshoffen/image-server:latest
    ports:
      - "8079:8079"