networks:
  task-tracker-net:
    driver: bridge

include:
  - docker-compose-db.yml
  - docker-compose-kafka.yml
  - docker-compose-front.yml

services:
  config-server:
    container_name: config-server
    image: mrshoffen/task-tracker-config-server:latest
    networks:
      - task-tracker-net
    ports:
      - "8012:8012"
    env_file:
      - ./vars.env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8012/actuator/health/readiness" ]
      interval: 5s
      timeout: 4s
      retries: 10
      start_period: 5s

  discovery-service:
    container_name: discovery-service
    image: mrshoffen/task-tracker-discovery-service:latest
    networks:
      - task-tracker-net
    ports:
      - "8015:8015"
    env_file:
      - ./vars.env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8015/actuator/health/readiness" ]
      interval: 5s
      timeout: 2s
      retries: 10
      start_period: 5s
    depends_on:
      config-server:
        condition: service_healthy

  user-profile-ws:
    container_name: user-profile-ws
    image: mrshoffen/task-tracker-user-profile:latest
    networks:
      - task-tracker-net
    env_file:
      - ./vars.env
    depends_on:
      discovery-service:
        condition: service_healthy
      postgres:
        condition: service_started
      kafka-ui:
        condition: service_started

  workspace-manager-rs:
    container_name: workspace-manager-rs
    image: mrshoffen/task-tracker-workspace-manager:latest
    networks:
      - task-tracker-net
    env_file:
      - ./vars.env
    depends_on:
      discovery-service:
        condition: service_healthy
      postgres:
        condition: service_started
      kafka-ui:
        condition: service_started

  desk-manager-rs:
    container_name: desk-manager-rs
    image: mrshoffen/task-tracker-desk-manager:latest
    networks:
      - task-tracker-net
    env_file:
      - ./vars.env
    depends_on:
      discovery-service:
        condition: service_healthy
      postgres:
        condition: service_started
      kafka-ui:
        condition: service_started

  task-manager-rs:
    container_name: task-manager-rs
    image: mrshoffen/task-tracker-task-manager:latest
    networks:
      - task-tracker-net
    env_file:
      - ./vars.env
    depends_on:
      discovery-service:
        condition: service_healthy
      postgres:
        condition: service_started
      kafka-ui:
        condition: service_started

  aggregator-rs:
    container_name: aggregator-rs
    image: mrshoffen/task-tracker-aggregator-service:latest
    networks:
      - task-tracker-net
    env_file:
      - ./vars.env
    depends_on:
      discovery-service:
        condition: service_healthy
      postgres:
        condition: service_started
      kafka-ui:
        condition: service_started

  user-permission-rs:
    container_name: user-permission-rs
    image: mrshoffen/task-tracker-user-permission-service:latest
    networks:
      - task-tracker-net
    env_file:
      - ./vars.env
    depends_on:
      discovery-service:
        condition: service_healthy
      postgres:
        condition: service_started
      kafka-ui:
        condition: service_started

  task-comments-rs:
    container_name: task-comments-rs
    image: mrshoffen/task-tracker-comments:latest
    networks:
      - task-tracker-net
    env_file:
      - ./vars.env
    depends_on:
      discovery-service:
        condition: service_healthy
      postgres:
        condition: service_started
      kafka-ui:
        condition: service_started


  task-sticker-rs:
    container_name: task-sticker-rs
    image: mrshoffen/task-tracker-stickers:latest
    networks:
      - task-tracker-net
    env_file:
      - ./vars.env
    depends_on:
      discovery-service:
        condition: service_healthy
      postgres:
        condition: service_started
      kafka-ui:
        condition: service_started

  task-realtime-service:
    container_name: task-realtime-service
    image: mrshoffen/task-tracker-realtime-service:latest
    networks:
      - task-tracker-net
    env_file:
      - ./vars.env
    depends_on:
      discovery-service:
        condition: service_healthy
      postgres:
        condition: service_started
      kafka-ui:
        condition: service_started

  authentication-service-1:
    container_name: authentication-service-1
    image: mrshoffen/task-tracker-authentication-service:latest
    networks:
      - task-tracker-net
    env_file:
      - ./vars.env
    depends_on:
      discovery-service:
        condition: service_healthy
      postgres:
        condition: service_started
      kafka-ui:
        condition: service_started

  authentication-service-2:
    container_name: authentication-service-2
    image: mrshoffen/task-tracker-authentication-service:latest
    networks:
      - task-tracker-net
    env_file:
      - ./vars.env
    depends_on:
      discovery-service:
        condition: service_healthy
      postgres:
        condition: service_started
      kafka-ui:
        condition: service_started

  authentication-service-3:
    container_name: authentication-service-3
    image: mrshoffen/task-tracker-authentication-service:latest
    networks:
      - task-tracker-net
    env_file:
      - ./vars.env
    depends_on:
      discovery-service:
        condition: service_healthy
      postgres:
        condition: service_started
      kafka-ui:
        condition: service_started

  mail-service:
    container_name: mail-service
    image: mrshoffen/task-tracker-mail-service:latest
    networks:
      - task-tracker-net
    env_file:
      - ./vars.env
    depends_on:
      discovery-service:
        condition: service_healthy
      postgres:
        condition: service_started
      kafka-ui:
        condition: service_started

  scheduler-1:
    container_name: scheduler-1
    image: mrshoffen/task-tracker-scheduler:latest
    networks:
      - task-tracker-net
    env_file:
      - ./vars.env
    depends_on:
      discovery-service:
        condition: service_healthy
      postgres:
        condition: service_started
      kafka-ui:
        condition: service_started

  scheduler-2:
    container_name: scheduler-2
    image: mrshoffen/task-tracker-scheduler:latest
    networks:
      - task-tracker-net
    env_file:
      - ./vars.env
    depends_on:
      discovery-service:
        condition: service_healthy
      postgres:
        condition: service_started
      kafka-ui:
        condition: service_started

  scheduler-3:
    container_name: scheduler-3
    image: mrshoffen/task-tracker-scheduler:latest
    networks:
      - task-tracker-net
    env_file:
      - ./vars.env
    depends_on:
      discovery-service:
        condition: service_healthy
      postgres:
        condition: service_started
      kafka-ui:
        condition: service_started


  api-gateway:
    container_name: api-gateway
    image: mrshoffen/task-tracker-api-gateway:latest
    networks:
      - task-tracker-net
    ports:
      - "8080:8080"
    env_file:
      - ./vars.env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health/readiness" ]
      interval: 5s
      timeout: 2s
      retries: 10
      start_period: 5s
    depends_on:
      - user-profile-ws
      - authentication-service-1
      - authentication-service-2
      - authentication-service-3
