networks:
  task-tracker-net:
    external: true

services:
  postgres:
    container_name: postgres_task
    image: postgres:17
    networks:
      - task-tracker-net
    env_file:
      - ./vars.env

  redis:
    container_name: redis_task
    image: redis:7.4
    networks:
      - task-tracker-net
    env_file:
      - ./vars.env