services:
  postgres-scheduler:
    container_name: postgres_scheduler
    image: postgres:17
    ports:
      - "3535:5432"
    networks:
      - task-tracker-net
    env_file:
      - ./vars.env
    environment:
      POSTGRES_DB: scheduler_db

  postgres-workspace:
    container_name: postgres_workspace
    image: postgres:17
    networks:
      - task-tracker-net
    env_file:
      - ./vars.env
    environment:
      POSTGRES_DB: workspace_db

  postgres-desk:
    container_name: postgres_desk
    image: postgres:17
    networks:
      - task-tracker-net
    env_file:
      - ./vars.env
    environment:
      POSTGRES_DB: desk_db

  postgres-task:
    container_name: postgres_tasks
    image: postgres:17
    networks:
      - task-tracker-net
    env_file:
      - ./vars.env
    environment:
      POSTGRES_DB: task_db

  postgres-permission:
    container_name: postgres_permission
    image: postgres:17
    networks:
      - task-tracker-net
    env_file:
      - ./vars.env
    environment:
      POSTGRES_DB: permission_db

  postgres-sticker:
    container_name: postgres_stickers
    image: postgres:17
    networks:
      - task-tracker-net
    env_file:
      - ./vars.env
    environment:
      POSTGRES_DB: stickers_db

  postgres-users:
    container_name: user_db
    image: postgres:17
    networks:
      - task-tracker-net
    env_file:
      - ./vars.env
    environment:
      POSTGRES_DB: user_db

  postgres-comment:
    container_name: postgres_comments
    image: postgres:17
    networks:
      - task-tracker-net
    env_file:
      - ./vars.env
    environment:
      POSTGRES_DB: postgres_comments

  redis:
    container_name: redis_task
    image: redis:7.4
    networks:
      - task-tracker-net
    env_file:
      - ./vars.env