services:
  task-frontend-service:
    container_name: task-frontend
    image: mrshoffen/task-tracker-frontend:latest
    ports:
      - "80:80"
    networks:
      - task-tracker-net
    env_file:
      - ./vars.env