services:
  postgres:
    container_name: postgres_task
    image: postgres:17
    ports:
      - "3535:5432"
    networks:
      - task-tracker-net
    env_file:
      - ./vars.env
    environment:
      POSTGRES_DB: task_db


  postgres-workspace:
    container_name: postgres_workspace
    image: postgres:17
    networks:
      - task-tracker-net
    env_file:
      - ./vars.env
    environment:
      POSTGRES_DB: workspace_db


  redis:
    container_name: redis_task
    image: redis:7.4
    networks:
      - task-tracker-net
    env_file:
      - ./vars.env